### ISSUE TITLE
alignment is not passed to buddy_sizeof

### ISSUE THREAD

**Issue by photoszzt** [spaskalev/buddy_alloc#69]
**Describe the bug**
https://github.com/spaskalev/buddy_alloc/blob/137b302e133468a001f061911f86df70bf0c6d07/buddy_alloc.h#L452
The alignment is not passed to the buddy_sizeof. It should be buddy_sizeof_alignment. 

**Expected behavior**

**To Reproduce**
Provide a minimal code example that demonstrates the bug.

**Comment by spaskalev** [comment]
Thanks, this is similar to the previous one but less critical as the check there will trigger only when the resulting effective memory size is zero. Because in the previous lines memory is trimmed to the actual set alignment this will either pass or in case the alignment is larger than memory this will result is a zero size and the check will fail.

**Comment by spaskalev** [comment]
See https://github.com/spaskalev/buddy_alloc/pull/70
